import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/app/header/Header";
import Footer from "@/app/footer/Footer";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="cupcake">

      <body className={inter.className}>
      <header>
        <Header />
      </header>
        <main>
          {children}
        </main>
      <footer>
        <Footer />
      </footer>
      </body>

    </html>
  )
}
